### ISSUE TITLE
Got general server error when editing role from restricted to privileged

### ISSUE THREAD

**Issue by ctrance** [mobilizingcs/admin#14]
Admin (mwf.cathy) check the box for 'ctrance1' then clicked the 'restricted' button then got 'General Server' error. The role changed from restricted to privileged though.

**Comment by stevenolen** [comment]
ah yes, I saw this on thursday and forgot about it.  For some reason I'm generating two requests to the server for the same user and one is being rejected because the db is locked while writing the state of the other!

Thank you for reporting!

**Comment by stevenolen** [comment]
@ctrance could you try this again? should be fixed.

**Comment by ctrance** [comment]
fixed now!
